var files =
[
    [ "/home/user/PAMSI/Array.cpp", null, null ],
    [ "/home/user/PAMSI/Array.hh", null, null ],
    [ "/home/user/PAMSI/Array2.cpp", null, null ],
    [ "/home/user/PAMSI/ArrayRunner.cpp", null, null ],
    [ "/home/user/PAMSI/ArrayRunner.hh", null, null ],
    [ "/home/user/PAMSI/ArrayTests.cpp", null, null ],
    [ "/home/user/PAMSI/EmptyQueueException.hh", null, null ],
    [ "/home/user/PAMSI/EmptyStackException.hh", null, null ],
    [ "/home/user/PAMSI/IArray.hh", null, null ],
    [ "/home/user/PAMSI/IList.hh", null, null ],
    [ "/home/user/PAMSI/IndexOutOfRangeException.hh", null, null ],
    [ "/home/user/PAMSI/IQueue.hh", null, null ],
    [ "/home/user/PAMSI/IRunnable.hh", null, null ],
    [ "/home/user/PAMSI/IStack.hh", null, null ],
    [ "/home/user/PAMSI/IStoper.hh", null, null ],
    [ "/home/user/PAMSI/List.cpp", null, null ],
    [ "/home/user/PAMSI/List.hh", null, null ],
    [ "/home/user/PAMSI/List2.hh", null, null ],
    [ "/home/user/PAMSI/ListTest.cpp", null, null ],
    [ "/home/user/PAMSI/ListTest.hh", null, null ],
    [ "/home/user/PAMSI/Main.cpp", null, null ],
    [ "/home/user/PAMSI/Queue.cpp", null, null ],
    [ "/home/user/PAMSI/Queue.hh", null, null ],
    [ "/home/user/PAMSI/Stack.cpp", null, null ],
    [ "/home/user/PAMSI/Stack.hh", null, null ],
    [ "/home/user/PAMSI/tab.cpp", null, null ],
    [ "/home/user/PAMSI/Test.cpp", null, null ],
    [ "/home/user/PAMSI/TimeCounter.cpp", null, null ],
    [ "/home/user/PAMSI/TimeCounter.hh", null, null ],
    [ "/home/user/PAMSI/.metadata/.plugins/org.eclipse.cdt.make.core/specs.c", null, null ],
    [ "/home/user/PAMSI/.metadata/.plugins/org.eclipse.cdt.make.core/specs.cpp", null, null ]
];